version: "3.8"
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    networks:
     - ecommerce-network
    volumes:
      - "./data/mongo:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
  mongoExpress:
    depends_on:
      - mongodb
    image: mongo-express
    restart: always
    volumes:
      - "./data/express:/data/db"
    ports:
      - '8081:8081'
    networks:
     - ecommerce-network
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
  mysqldb:
    image: mysql
    restart: unless-stopped
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"
    networks:
      - ecommerce-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysqldb
    ports:
      - "8080:80"
    depends_on:
      - mysqldb
    networks:
      - ecommerce-network

  keycloak-server:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    volumes:
      - "./data/keycloak:/var/lib/keycloak/data"

    environment:
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 3306
      KC_DB_URL_HOST: mysqldb
      KC_HOSTNAME_STRICT: false
      KC_DB: mysql #database vendor name
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
    ports:
      - "8181:8080"
    depends_on:
      - mysqldb
    networks:
      - ecommerce-network


networks:
  ecommerce-network: